version: "3.8"
services:
  backend:
    build: ./backend
    container_name: toolnet-backend
    ports:
      - "5000:5000"
    env_file:
      - ./backend/.env


  frontend:
    build: .
    container_name: toolnet-frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend    