apiVersion: v1
kind: Secret
metadata:
  name: toolnet-secrets
type: Opaque 
stringData:
  EMAIL_USER: "thotasruthi15@gmail.com"
  EMAIL_PASS: "gxrdfxsbxanemlym"
  MONGO_URI: "mongodb+srv://sru15:tool1234@cluster0.zvell.mongodb.net/toolbank?"